"""Turn this machine's Earth Engine OAuth credentials into the TOML block that
Streamlit Community Cloud's Settings > Secrets box expects.

The deployed app has no ~/.config/earthengine/credentials to read, so it gets
the same refresh token from st.secrets instead (see drive_client.py). Copying
those fields by hand from JSON into TOML is easy to get subtly wrong, so:

    python make_secrets.py

writes .streamlit/secrets.toml - which is gitignored, and stays that way.
Open it, copy the whole contents, paste into the app's Secrets box. Nothing is
printed to the terminal, because the refresh token is a real credential: it
grants Drive access to this Google account until revoked.

Revoke it any time at https://myaccount.google.com/permissions
"""
import json
import os
import sys

CRED_PATH = os.path.expanduser("~/.config/earthengine/credentials")
OUT_PATH = os.path.join(".streamlit", "secrets.toml")

# Scopes the dashboard's Drive read path needs. Kept in sync with
# .streamlit/secrets.toml.example.
SCOPES = [
    "https://www.googleapis.com/auth/earthengine",
    "https://www.googleapis.com/auth/cloud-platform",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/devstorage.full_control",
]


def main() -> int:
    if not os.path.exists(CRED_PATH):
        print(f"No credentials at {CRED_PATH}.\n"
              "Run 'earthengine authenticate' once, then re-run this.", file=sys.stderr)
        return 1

    with open(CRED_PATH, encoding="utf-8") as f:
        cred = json.load(f)

    if "refresh_token" not in cred:
        print(f"{CRED_PATH} has no refresh_token - re-run 'earthengine authenticate'.",
              file=sys.stderr)
        return 1

    lines = ["# Generated by make_secrets.py - do not commit (already gitignored).",
             "# Paste the whole file into Streamlit Cloud > Settings > Secrets.",
             "", "[gcp_drive]",
             f'refresh_token = "{cred["refresh_token"]}"']
    # client_id/client_secret are optional: drive_client falls back to Earth
    # Engine's public installed-app identifiers when they're absent.
    for key in ("client_id", "client_secret"):
        if cred.get(key):
            lines.append(f'{key} = "{cred[key]}"')
    lines.append("scopes = [")
    lines += [f'    "{s}",' for s in cred.get("scopes") or SCOPES]
    lines.append("]")

    os.makedirs(".streamlit", exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH} ({len(lines)} lines). Open it, copy all of it into "
          "the Streamlit Cloud Secrets box. It is gitignored - keep it that way.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
